services:
  cheollian-server:
    image: adorableco/cheollian:latest
    restart: unless-stopped
    container_name: cheollian-server
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8080:8080"