server:
  port: ${SPRING_PORT}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  ai.openai:
    api-key: ${OPENAI_API_KEY}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope: email, profile

app:
  jwt:
    secret: ${JWT_SECRET}
    bearer-type: Bearer
    auth-header: Authorization
    expiration:
      access: 259200    # 60 * 60 * 24 * 3 (3 days in seconds)
      refresh: 1296000  # 60 * 60 * 24 * 15 (15 days in seconds)
  auth:
    redirect-uri: ${OAUTH2_REDIRECT_URI}

cloud:
  project-id: ${CLOUD_PROJECT_ID}
  bucket: ${CLOUD_BUCKET_NAME}

school:
  key: ${SCHOOL_KEY}

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
