name: develop-ci

on:
  pull_request:
    branches:
      - 'main'

permissions: write-all

jobs:
  setting:
    runs-on: ubuntu-latest
    env:
      SPRING_PORT: ${{secrets.SPRING_PORT}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      DB_DATABASE: ${{secrets.DB_DATABASE}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_ROOT_PASSWORD: ${{secrets.DB_ROOT_PASSWORD}}
      DB_HOST: ${{secrets.DB_HOST}}
      DB_PORT: ${{secrets.DB_PORT}}
      OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew


      - name: Test with Gradle
        run: ./gradlew clean test

